CREATE SCHEMA IF NOT EXISTS estacionamento;

use estacionamento;

CREATE TABLE IF NOT EXISTS dUsuario (
	LOGIN VARCHAR(50) PRIMARY KEY NOT NULL,
	SENHA varchar(100) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	FUNCAO NUMERIC(1) null,
	DESCRICAO_FUNCAO VARCHAR(50) NOT NULL,
	TELEFONE varchar(11) null
);

 CREATE TABLE IF NOT EXISTS dCliente (
	IDCLIENTE INTEGER NOT NULL AUTO_INCREMENT,
	DTNASC date NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF char(11),
	CNPJ char(14),
	SEXO CHAR(1),
	TELEFONE varchar(11) NOT NULL,
	TIPO_CLIENTE INTEGER,
	EMAIL VARCHAR(100) NOT NULL,
	senha varchar(100) not null,
	NOME_RUA VARCHAR(100),
	NUMERO_CASA INTEGER,
	COMPLEMENTO VARCHAR(10),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(2),
	CEP INTEGER,
	status boolean null,
	primary key(IDCLIENTE, EMAIL)
);

CREATE TABLE IF NOT EXISTS dPlanos (
	VALOR NUMERIC(15,2) NOT NULL,
	DESCRICAO_PLANO VARCHAR(50),
	IDPLANO INTEGER PRIMARY KEY AUTO_INCREMENT,
	placa varchar(7) not null
);
		
 CREATE TABLE IF NOT EXISTS dVeiculo (
	PLACA VARCHAR(7) PRIMARY KEY NOT NULL,
	MARCA VARCHAR(20),
	MODELO VARCHAR(20),
	COR VARCHAR(20) NOT NULL,
	TIPO_VEICULO INTEGER,
	DESCRICAO_TIPO VARCHAR(50),
	OBSERVACOES VARCHAR(100),
	IDCLIENTE INTEGER not null,
	idplano int not null,
	foreign key(idplano)
		references dPlanos(IDPLANO),
	foreign key(IDCLIENTE)
		references dCliente(IDCLIENTE)
);

 CREATE TABLE IF NOT EXISTS dVagas (
	IDVAGA INTEGER PRIMARY KEY AUTO_INCREMENT,
	TIPO_VAGA INTEGER NOT NULL,
	DESCRICAO_VAGA VARCHAR(50),
	STATUS_VAGA INTEGER
);

CREATE TABLE IF NOT EXISTS fRotativo (
	IDROTATIVO INTEGER PRIMARY KEY AUTO_INCREMENT,
	LOGIN VARCHAR(50),
	IDVAGA INTEGER,
	IDCLIENTE VARCHAR(10),
	IDPLANO INTEGER,
	PLACA VARCHAR(7),
	DTHR_ENTRADA DATETIME,
	DTHR_SAIDA DATETIME,
	VALOR_ESTADIA NUMERIC(15),
	FOREIGN KEY (LOGIN) REFERENCES dUsuario (LOGIN),
	FOREIGN KEY (IDVAGA) REFERENCES dVagas (IDVAGA),
	FOREIGN KEY (IDCLIENTE) REFERENCES dCliente (IDCLIENTE),
	FOREIGN KEY (IDPLANO) REFERENCES dPlanos (IDPLANO),
	FOREIGN KEY (PLACA) REFERENCES dVeiculos (PLACA)
);

CREATE TABLE IF NOT EXISTS fPagamento (
	IDPGTO INTEGER PRIMARY KEY,
	DESCRICAO_TIPO_PGTO VARCHAR(50),
	TIPO_PGTO INTEGER,
	IDCLIENTE INTEGER,
	PLACA VARCHAR(7),
	IDROTATIVO INTEGER,
	IDPLANO INTEGER,
	VALOR_PGTO NUMERIC(15,2),
    FOREIGN KEY (PLACA) REFERENCES dVeiculos (PLACA),
    FOREIGN KEY (IDCLIENTE) REFERENCES dCliente (IDCLIENTE),
    FOREIGN KEY (IDROTATIVO) REFERENCES dRotativo (IDROTATIVO)
);